### PR TITLE
Adds support for gradients to line charts

### PR DESCRIPTION
**Pull request by benjaminsnorris**
This adds support via the delegate protocol for displaying a gradient for the line and fill of any line in a line chart view.

### CODE REVIEW

**Comment by myusuf3** [comment]
@benjaminsnorris will this allow for something similar to this if the correct gradient is provided? 

This higher something get the brighter it will be? e.g.

screen shot 2015-06-18 at 2 24 10 pm

**Comment by benjaminsnorris** [comment]
@myusuf3 Absolutely. You would just pass in a vertical gradient, and it would use that gradient for the line color. That's a great use case for what I had in mind!

**Comment by myusuf3** [comment]
@terryworona any chance we could get this in?

**Comment by terryworona** [comment]
Pretty neat feature!

My 2c: instead of requesting a gradient layer, how about exposing a start and end color for a gradient at line index?

Something like...

    - (UIColor *)lineChartView:(JBLineChartView *)lineChartView startColorForLineAtLineIndex:(NSUInteger)lineIndex;
    - (UIColor *)lineChartView:(JBLineChartView *)lineChartView endColorForLineAtLineIndex:(NSUInteger)lineIndex;

If startColor && endColor are != nil, then create a gradient layer (internally - private), otherwise, revert to the regular colorForLine (which eventually defaults to black). 

With this, we can eliminate the need for JBLineChartViewLineColorStyle.

The only thing we lose is the direction of the gradient; but this could be exposed via a JBLineChartViewLineGradientDirection enum?

Lastly, a question - do we have to swap out layers when a selection occurs? Can we not just set the selectedGradient or selectedFillGradient's color's property like we do with shape layers?

**Comment by benjaminsnorris** [comment]
Terry, great feedback. I think it's fine to simplify a bit and just expose colors in the delegate. I'll probably do a start, mid, and end as that's what I need. :) My thought with accepting the gradient is to allow for maximum flexibility, just like with the `UIView` for a dot. But, you make a great point with the selection. Going this route would allow us to just hang on to the gradient and change the colors. I'll rework it soon to make the changes you suggested and then ping you again. Thanks!

**Comment by terryworona** [comment]
@benjaminsnorris I totally get the correlation between CAGradientLayer and UIView. It's a toss up for sure. But I see custom dot views as self-contained elements, whereas an entire graph gradient is a bit more involved. 

Look forward to seeing the changes and pulling this in!

**Comment by timshadel** [comment]
Start color and end color aren't enough. You need to allow for more than two colors plus positions for the changes that each of those colors make their transitions. If you look at the properties of CAGradientLayer, they're a perfect fit to model a gradient. I suppose if you are worried about the "layer" part then an identical model class without the layer would be good, but start color and end color would not be enough for what is like to do with it.

**Comment by terryworona** [comment]
Finally found some time to re-open this. 

Pulled it in, cleaned it up a little bit and added gradient support for bar charts as well (see screenshots). 

I decided to go with CAGradientLayer objects for both chart types. @benjaminsnorris & @timshadel  I totally agree that it gives the most flexibility. 

I should have this pushed to master and finished up by the weekend!

**Comment by terryworona** [comment]
For those that can't wait, check out the branch: https://github.com/Jawbone/JBChartView/tree/benjaminsnorris-add-line-gradient-support

Comments welcome!

**Comment by terryworona** [comment]
@benjaminsnorris can you explain this comment you added:

    Alpha of gradient is controlled by the color returned from lineChartView:fillColorForLineAtLineIndex

I don't really understand how this alpha relates to gradients? This comment is used in the gradient line and selection fills as well. 

I looked through the implementation and couldn't find evidence of this being used.

**Pull request merged**
