### PR TITLE
Add ability to have the line start or end at any given point

### PR DESCRIPTION
**Pull request by sebastianreloaded**
This pull requests adds the ability to have the line start or end at any given point.
Now lineChartView: verticalValueForHorizontalIndex: atLineIndex: can return NAN as a value and the line starts at the first non-nan value and ends at the last non-nan value.

i also added an example.

### CODE REVIEW

**Comment by sebastianreloaded** [comment]
@terryworona 
hi, do you plan on merging this anytime soon or can i do anything to help?

**Comment by terryworona** [comment]
Sorry for not getting to this until now. It's a very good addition. I've made some comments and we need to address the crashes. 

As well, can you update the README with some information on NaN support?

**Comment by sebastianreloaded** [comment]
hi, thanks for the reply. i'll look into it later this week and fix your points, as well as update the README.

**Comment by vocaro** [comment]
Just wanted to say I've been testing this PR for a couple weeks and it's been working great for me. +1 on merging.

**Comment by terryworona** [comment]
Cool, just waiting on those last changes then it can be merged. I'll be away from computer for a few weeks, so take your time!

**Comment by mingfu** [comment]
Could really use this functionality as I'm looking for ways to hack around this right now while still using JBChartView

**Comment by terryworona** [comment]
Thanks for these fixes. Pulling it in!

**Pull request merged**
