### PR TITLE
Fix crash and performance issues when not animating

### PR DESCRIPTION
**Pull request by Autoc0diq**
- Fix crash when calling reloadDataAnimated:YES immediately when barViews is still nil causing an out of bounds index crash.
- Fixed performance issues when calling reloadData. Removing and reading subviews can be very expensive especially with auto-layout.

### CODE REVIEW

**Comment by zadr** [comment]
This may not be important, but there's a fairly subtle change here that's led to conditions that've caused me to spend memorable amounts of time tracking down bugs:

Basically: if an animation duration is `0.0`, the `completion()` of an animation doesn't get called until the next runloop (as if `[self performSelector:@selector(completion) afterDelay:0]` was called instead).

(The longer version of this story involves a race condition in a single-threaded app, a `weak` reference to a controller, a funky transition, and some amount of (bad) luck depending on cache and networking conditions.)

((The whitespace-independent diff is easier to read: https://github.com/Autoc0diq/JBChartView-Fix/commit/c5f1e679db43fba282faccd5fa3207a93af25b79?w=1))

**Comment by Autoc0diq** [comment]
Ok. One issue though is that the reload without animation does not actually try to reuse the view and thus leads to very bad performance which is why I was trying to reuse the animation blocks.

The second issue though is more problematic is the crash when calling reloadDataAnimated:YES first because `weakSelf.barViews` is initially nil then.

**Comment by terryworona** [comment]
The performance issues along with you proposed solution need only a few small tweaks in order to address @zadr's concerns (which I have experienced myself). 

I'm more concerned with this crash you speak of. What are the exact steps to reproduce? Just call reloadDataAnimated:YES before any initial reloadData is called?

**Comment by zadr** [comment]
@Autoc0diq: while those both sound bad, please note that I'm not a maintainer of JBChartView, and it probably makes sense wait and see what @terryworona has to say about everything. (there may be some other behavior or intention that we're missing)

**Comment by Autoc0diq** [comment]
@terryworona yes calling `reloadDataAnimated:YES` first will cause the crash because `weakSelf.barViews` is nil and calling `[weakSelf.barViews arrayByAddingObject:barView]` returns nil and thus the first bar yields an empty array `weakSelf.barViews`

**Comment by terryworona** [comment]
Fixed with commit: eacc211dbd14929bedce4bc51a31a111c59df15d

version: [3.0.7](https://github.com/Jawbone/JBChartView/tree/v3.0.7)

I fixed the crash by instantiating the barViews collection on view instantiations. 

The performance issues should also be alleviated; I reused the animated code but avoid any animation blocks.

**Pull request closed without merging**
