### PR TITLE
+ reloadEndedInBarChartView: delegate added

### PR DESCRIPTION
**Pull request by bw0lff**
Added a delegate that allows us to have a feedback on when the reload of a chart has finished.
Might be useful for terminating load animations for example.

### CODE REVIEW

**Comment by terryworona** [comment]
Reload data is a synchronous call that occurs in near-constant time.

I just don't see how this callback would be useful? Perhaps you can further explain?

**Comment by bw0lff** [comment]
Is it farfetched to have a callback for the end of a reload action?
Lets say I need to do some work after the chart being loaded, and that the
reload can be called in several places...
A delegate would be handy in this situation right? Not to provide async
support, but to enable us to have the code we need... where is needed...

The reason I spoke about loading is due to a bottleneck I use to have on my
app (I had to do some heavy data generation while graphs where being
drawn). In this case, the graphs use to take some time to reload (mainly in
old devices...).

Cheers,
Jorge Miguel

**Comment by terryworona** [comment]
It think it is a bit farfetched to have callbacks for synchronous operations that happen in near-real time. 

I've populated charts with 1000+ items and haven't had any hiccup. Unless your spawning off an async block to reload data, you shouldn't need this. 

Does UITableView have a reloadData:callback:? :)

**Comment by terryworona** [comment]
Closing this guy for now....thanks for the contribution thought! 

I just can't see a use for it right now. IMO if reloadData is taking so long you need a callback, it's likely time to re-assess your data source and consolidate.

**Pull request closed without merging**
